### ISSUE TITLE
I Prodotti variabili non hanno l'attributo nel nome

### ISSUE THREAD

**Issue by salvymc** [ilGhera/wc-exporter-for-danea#1]
I Prodotti variabili non hanno l'attributo nel nome, questo rende difficile scaricare i prodotti durante la vendita a banco di Danea

**Comment by salvymc** [comment]
Ho aggiunto una soluzione qui #2

**Comment by ilGhera** [comment]
Ciao @salvymc 
grazie per il tuo contributo.
Condivido, indicare nel nome del prodotto in Danea gli attributi, ovvero le caratteristiche della variazione di prodotto, toglie confusione ed aiuta l'operatore nelle attività quotidiane.
Ho applicato delle modifiche al tuo codice che ti invito a rivedere e commentare se necessario.
Grazie.

**Comment by salvymc** [comment]
Ciao Andrea, grazie per la risposta, questa sera do un occhiata alle
modifiche.

Il gio 29 set 2022, 15:22 Andrea Gherardi ***@***.***> ha
scritto:

**Comment by salvymc** [comment]
Perfetto, ho testato la soluzione su un e-commerce con più di 3000 prodotti misti (semplici, variabili) ed è tutto OK !! 😎

![asassa](https://user-images.githubusercontent.com/10051897/193118281-b31702d5-6b8e-41a4-9112-4062175394c7.PNG)

**Comment by ilGhera** [comment]
Ciao @salvymc 
ottimo, grazie per il test e per il riscontro.
